import * as React from "react";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

// ============================================================
// DATA MODELS
// ============================================================

export interface TaskResource {
  title: string;
  url: string;
}

export type TaskStatus = "locked" | "unlocked" | "completed";

export interface Task {
  id: string;
  title: string;
  description: string;
  whyItMatters: string;
  howToDoThis: string;
  resources: TaskResource[];
  status: TaskStatus;
}

export interface ProgressUpdate {
  id: string;
  content: string;
  createdAt: string;
}

export interface Roadmap {
  id: string;
  goal: string;
  goalCategory: string;
  yearInSchool: string;
  major: string;
  school: string;
  isInternational: boolean;
  degree: string;
  currentExperience: string;
  additionalContext: string;
  tasks: Task[];
  updates: ProgressUpdate[];
  createdAt: string;
}

export interface WizardFormData {
  yearInSchool: string;
  major: string;
  school: string;
  isInternational: string;
  degree: string;
  currentExperience: string;
  goal: string;
  additionalContext: string;
}

// ============================================================
// TASK TEMPLATES
// Placeholder: In the future, these would be generated by AI based on user profile
// ============================================================

const TASK_TEMPLATES: Record<string, Omit<Task, "id" | "status">[]> = {
  consulting: [
    {
      title: "Identify 10 Target Firms",
      description: "Research and list 10 consulting firms that align with your goals and hire international students.",
      whyItMatters: "Having a focused target list prevents scattered effort and helps you build deep knowledge about firms you actually want to join.",
      howToDoThis: "Start with MBB (McKinsey, BCG, Bain), then add Big 4 consulting arms and boutique firms. Check their H-1B sponsorship history on myvisajobs.com.",
      resources: [
        { title: "Consulting Firm Rankings", url: "https://www.vault.com/best-companies-to-work-for/consulting" },
        { title: "H-1B Sponsorship Database", url: "https://www.myvisajobs.com" },
      ],
    },
    {
      title: "Perfect Your Consulting Resume",
      description: "Reformat your resume to match consulting standards with quantified impact statements.",
      whyItMatters: "Consulting firms receive thousands of applications. A properly formatted resume with clear impact metrics is essential to pass the initial screen.",
      howToDoThis: "Use the 'accomplished X by doing Y resulting in Z' format. Lead with action verbs. Keep to one page. Have 3 people review it.",
      resources: [
        { title: "McKinsey Resume Guide", url: "https://www.mckinsey.com/careers/search-for-jobs" },
      ],
    },
    {
      title: "Connect with 3 Alumni in Consulting",
      description: "Reach out to alumni from your school working at target firms for informational interviews.",
      whyItMatters: "Alumni are 10x more likely to respond than cold contacts. These conversations give you insider knowledge and potential referrals.",
      howToDoThis: "Use LinkedIn to find alumni at target firms. Send a personalized message referencing your shared school experience. Ask for 20 minutes of their time.",
      resources: [
        { title: "LinkedIn Alumni Search", url: "https://www.linkedin.com/school/" },
      ],
    },
    {
      title: "Master Case Interview Basics",
      description: "Learn the fundamental frameworks and practice 5 cases with peers.",
      whyItMatters: "Case interviews are the core of consulting recruiting. Without solid case skills, even great networkers don't get offers.",
      howToDoThis: "Study the basic frameworks (profitability, market entry, M&A). Join a case prep group. Practice out loud, not just in your head.",
      resources: [
        { title: "Case Interview Prep", url: "https://www.preplounge.com" },
        { title: "Victor Cheng's Case Videos", url: "https://www.caseinterview.com" },
      ],
    },
    {
      title: "Attend a Consulting Info Session",
      description: "Register for and attend an on-campus or virtual recruiting event at a target firm.",
      whyItMatters: "Info sessions let you learn about firm culture, meet recruiters, and get your name on their radar before applications open.",
      howToDoThis: "Check your career center calendar and firm websites for upcoming events. Prepare 2-3 thoughtful questions to ask.",
      resources: [],
    },
  ],
  finance: [
    {
      title: "Build Your Target List of 10 Banks",
      description: "Create a prioritized list of investment banks and financial institutions that sponsor international students.",
      whyItMatters: "Finance recruiting is highly structured. Knowing exactly where to focus your energy maximizes your chances.",
      howToDoThis: "Research bulge bracket banks (Goldman, JPM, Morgan Stanley), elite boutiques (Evercore, Lazard), and middle market firms. Check H-1B data.",
      resources: [
        { title: "Wall Street Oasis Rankings", url: "https://www.wallstreetoasis.com" },
        { title: "H-1B Sponsorship Data", url: "https://www.myvisajobs.com" },
      ],
    },
    {
      title: "Format Resume for Finance",
      description: "Restructure your resume to highlight deal experience, financial modeling, and quantitative skills.",
      whyItMatters: "Finance resumes need specific formatting and keywords. Recruiters spend 6 seconds per resume—make yours stand out.",
      howToDoThis: "Put education and GPA prominently. Lead bullets with numbers. Highlight any transaction, valuation, or modeling experience.",
      resources: [
        { title: "Mergers & Inquisitions Resume Guide", url: "https://www.mergersandinquisitions.com" },
      ],
    },
    {
      title: "Connect with 3 Alumni in Finance",
      description: "Reach out to alumni working at target banks for informational interviews.",
      whyItMatters: "Referrals are crucial in finance. Alumni connections often lead to interview opportunities.",
      howToDoThis: "Use LinkedIn to find alumni analysts and associates. Be specific about why you're reaching out and what you want to learn.",
      resources: [],
    },
    {
      title: "Master Technical Interview Prep",
      description: "Study accounting, valuation, and financial modeling concepts for technical interviews.",
      whyItMatters: "Technical questions are pass/fail gates in finance interviews. You need instant recall on fundamentals.",
      howToDoThis: "Memorize the 400 questions guide. Practice walking through DCFs and comparable company analysis out loud.",
      resources: [
        { title: "400 Investment Banking Questions", url: "https://www.wallstreetprep.com" },
      ],
    },
    {
      title: "Apply to Summer Analyst Programs",
      description: "Submit applications to 5+ summer internship programs at target banks.",
      whyItMatters: "Summer analyst programs are the primary pipeline for full-time offers. Missing deadlines means missing opportunities.",
      howToDoThis: "Track application deadlines carefully—many open in August for the following summer. Apply early in the cycle.",
      resources: [],
    },
  ],
  tech: [
    {
      title: "Define Your Target Companies",
      description: "List 10 tech companies that match your interests and sponsor H-1B visas.",
      whyItMatters: "Tech has many paths—FAANG, startups, enterprise. Clarity on your targets helps focus your preparation.",
      howToDoThis: "Consider company size, product focus, and culture. Check Levels.fyi for compensation and visa sponsorship policies.",
      resources: [
        { title: "Levels.fyi Company Data", url: "https://www.levels.fyi" },
        { title: "Tech Company H-1B Data", url: "https://www.myvisajobs.com" },
      ],
    },
    {
      title: "Optimize Your Tech Resume",
      description: "Tailor your resume to highlight projects, technical skills, and quantified impact.",
      whyItMatters: "Tech resumes get screened by both ATS and recruiters. Clear project descriptions and skill keywords are essential.",
      howToDoThis: "Lead with your strongest projects. Quantify impact where possible. List relevant technologies prominently.",
      resources: [],
    },
    {
      title: "Connect with 3 Engineers at Target Companies",
      description: "Reach out to engineers for informational interviews about their experience and referrals.",
      whyItMatters: "Employee referrals significantly increase interview rates at tech companies.",
      howToDoThis: "Find connections through LinkedIn, GitHub, or tech meetups. Ask about their day-to-day and what makes candidates successful.",
      resources: [],
    },
    {
      title: "Complete LeetCode Fundamentals",
      description: "Solve 50 medium-difficulty problems covering core data structures and algorithms.",
      whyItMatters: "Technical interviews at top companies require strong problem-solving skills under time pressure.",
      howToDoThis: "Focus on arrays, trees, graphs, and dynamic programming. Practice explaining your thought process out loud.",
      resources: [
        { title: "LeetCode", url: "https://leetcode.com" },
        { title: "NeetCode Roadmap", url: "https://neetcode.io" },
      ],
    },
    {
      title: "Build a Side Project",
      description: "Create and deploy a project that demonstrates your technical skills and interests.",
      whyItMatters: "Projects show initiative and give you concrete examples to discuss in behavioral interviews.",
      howToDoThis: "Choose something you're genuinely interested in. Deploy it live. Be ready to explain design decisions.",
      resources: [],
    },
  ],
  general: [
    {
      title: "Define Your Career Goal",
      description: "Write a clear, specific statement of what role and industry you're targeting.",
      whyItMatters: "Clarity attracts opportunity. People can only help you if they understand what you're looking for.",
      howToDoThis: "Complete this sentence: 'I want to work as a [role] at a [type of company] in [industry] because [reason].'",
      resources: [],
    },
    {
      title: "Audit Your Resume",
      description: "Review your resume for clarity, impact, and alignment with your target role.",
      whyItMatters: "Your resume is often your first impression. It needs to clearly communicate your value.",
      howToDoThis: "Read each bullet and ask: 'So what?' If you can't answer, rewrite it with quantified impact.",
      resources: [],
    },
    {
      title: "Identify 5 Target Companies",
      description: "Research and list companies where you'd like to work that align with your goals.",
      whyItMatters: "Focused job searching is more effective than applying everywhere. Quality over quantity.",
      howToDoThis: "Consider company culture, growth trajectory, and visa sponsorship policies. Research employee reviews.",
      resources: [
        { title: "Glassdoor Company Reviews", url: "https://www.glassdoor.com" },
      ],
    },
    {
      title: "Reach Out to 3 Professionals",
      description: "Send personalized messages to professionals in your target field for informational interviews.",
      whyItMatters: "Networking opens doors that applications alone cannot. Most jobs are filled through connections.",
      howToDoThis: "Use LinkedIn to find alumni or second-degree connections. Be specific about what you want to learn.",
      resources: [],
    },
    {
      title: "Practice Your Elevator Pitch",
      description: "Prepare and rehearse a 30-second introduction that captures who you are and what you're seeking.",
      whyItMatters: "First impressions matter. A polished introduction builds confidence and opens conversations.",
      howToDoThis: "Structure: Present → Past → Future. Practice until it feels natural, not scripted.",
      resources: [],
    },
  ],
};

// ============================================================
// HELPER FUNCTIONS
// ============================================================

function detectGoalCategory(goal: string): string {
  // Placeholder: In the future, AI would classify the goal more intelligently
  const lowerGoal = goal.toLowerCase();
  if (lowerGoal.includes("consult") || lowerGoal.includes("mckinsey") || lowerGoal.includes("bcg") || lowerGoal.includes("bain")) {
    return "consulting";
  }
  if (lowerGoal.includes("bank") || lowerGoal.includes("finance") || lowerGoal.includes("investment") || lowerGoal.includes("goldman") || lowerGoal.includes("trading")) {
    return "finance";
  }
  if (lowerGoal.includes("tech") || lowerGoal.includes("software") || lowerGoal.includes("engineer") || lowerGoal.includes("google") || lowerGoal.includes("facebook") || lowerGoal.includes("amazon")) {
    return "tech";
  }
  return "general";
}

function generateTasks(goalCategory: string): Task[] {
  const templates = TASK_TEMPLATES[goalCategory] || TASK_TEMPLATES.general;
  return templates.map((template, index) => ({
    ...template,
    id: `task-${index + 1}`,
    status: index === 0 ? "unlocked" : "locked" as TaskStatus,
  }));
}

function generateId(): string {
  return `roadmap-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// ============================================================
// CONTEXT
// ============================================================

interface RoadmapContextType {
  roadmaps: Roadmap[];
  currentRoadmap: Roadmap | null;
  wizardFormData: WizardFormData;
  updateWizardFormData: (data: Partial<WizardFormData>) => void;
  createRoadmap: () => string;
  setCurrentRoadmap: (id: string) => void;
  completeTask: (taskId: string) => void;
  addProgressUpdate: (content: string) => void;
}

const defaultWizardFormData: WizardFormData = {
  yearInSchool: "",
  major: "",
  school: "",
  isInternational: "",
  degree: "",
  currentExperience: "",
  goal: "",
  additionalContext: "",
};

const RoadmapContext = createContext<RoadmapContextType | null>(null);

const STORAGE_KEY = "network-navigator-roadmaps";
const CURRENT_ROADMAP_KEY = "network-navigator-current";

export function RoadmapProvider({ children }: { children: ReactNode }) {
  const [roadmaps, setRoadmaps] = useState<Roadmap[]>([]);
  const [currentRoadmapId, setCurrentRoadmapId] = useState<string | null>(null);
  const [wizardFormData, setWizardFormData] = useState<WizardFormData>(defaultWizardFormData);

  // Load from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        setRoadmaps(JSON.parse(stored));
      } catch (e) {
        console.error("Failed to parse stored roadmaps", e);
      }
    }
    const storedCurrent = localStorage.getItem(CURRENT_ROADMAP_KEY);
    if (storedCurrent) {
      setCurrentRoadmapId(storedCurrent);
    }
  }, []);

  // Persist to localStorage on change
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(roadmaps));
  }, [roadmaps]);

  useEffect(() => {
    if (currentRoadmapId) {
      localStorage.setItem(CURRENT_ROADMAP_KEY, currentRoadmapId);
    }
  }, [currentRoadmapId]);

  const currentRoadmap = roadmaps.find((r) => r.id === currentRoadmapId) || null;

  const updateWizardFormData = (data: Partial<WizardFormData>) => {
    setWizardFormData((prev) => ({ ...prev, ...data }));
  };

  const createRoadmap = (): string => {
    const goalCategory = detectGoalCategory(wizardFormData.goal);
    const tasks = generateTasks(goalCategory);

    const newRoadmap: Roadmap = {
      id: generateId(),
      goal: wizardFormData.goal,
      goalCategory,
      yearInSchool: wizardFormData.yearInSchool,
      major: wizardFormData.major,
      school: wizardFormData.school,
      isInternational: wizardFormData.isInternational.toLowerCase() === "yes",
      degree: wizardFormData.degree,
      currentExperience: wizardFormData.currentExperience,
      additionalContext: wizardFormData.additionalContext,
      tasks,
      updates: [],
      createdAt: new Date().toISOString(),
    };

    setRoadmaps((prev) => [newRoadmap, ...prev]);
    setCurrentRoadmapId(newRoadmap.id);
    setWizardFormData(defaultWizardFormData);

    return newRoadmap.id;
  };

  const setCurrentRoadmap = (id: string) => {
    setCurrentRoadmapId(id);
  };

  const completeTask = (taskId: string) => {
    setRoadmaps((prev) =>
      prev.map((roadmap) => {
        if (roadmap.id !== currentRoadmapId) return roadmap;

        const taskIndex = roadmap.tasks.findIndex((t) => t.id === taskId);
        if (taskIndex === -1) return roadmap;

        const updatedTasks = roadmap.tasks.map((task, index) => {
          if (task.id === taskId) {
            return { ...task, status: "completed" as TaskStatus };
          }
          // Unlock the next task
          if (index === taskIndex + 1 && task.status === "locked") {
            return { ...task, status: "unlocked" as TaskStatus };
          }
          return task;
        });

        return { ...roadmap, tasks: updatedTasks };
      })
    );
  };

  const addProgressUpdate = (content: string) => {
    if (!content.trim()) return;

    const update: ProgressUpdate = {
      id: `update-${Date.now()}`,
      content: content.trim(),
      createdAt: new Date().toISOString(),
    };

    setRoadmaps((prev) =>
      prev.map((roadmap) => {
        if (roadmap.id !== currentRoadmapId) return roadmap;

        // Placeholder: In the future, AI would analyze the update and potentially
        // adjust task descriptions or add new tasks based on user progress
        const updatedTasks = roadmap.tasks.map((task, index) => {
          // Mock logic: If user mentions struggle, add encouraging note to next unlocked task
          if (task.status === "unlocked" && content.toLowerCase().includes("struggling")) {
            return {
              ...task,
              howToDoThis: task.howToDoThis + " Remember: progress over perfection. Even small steps count!",
            };
          }
          return task;
        });

        return {
          ...roadmap,
          tasks: updatedTasks,
          updates: [update, ...roadmap.updates],
        };
      })
    );
  };

  return (
    <RoadmapContext.Provider
      value={{
        roadmaps,
        currentRoadmap,
        wizardFormData,
        updateWizardFormData,
        createRoadmap,
        setCurrentRoadmap,
        completeTask,
        addProgressUpdate,
      }}
    >
      {children}
    </RoadmapContext.Provider>
  );
}

export function useRoadmap() {
  const context = useContext(RoadmapContext);
  if (!context) {
    throw new Error("useRoadmap must be used within a RoadmapProvider");
  }
  return context;
}
